//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AxMonthlyData
    {
        public Nullable<decimal> PurchCount { get; set; }
        public Nullable<decimal> NetAmountInUSD { get; set; }
        public Nullable<decimal> AssetCount { get; set; }
        public Nullable<decimal> AssetValuationCount { get; set; }
        public Nullable<decimal> BreakfixCount { get; set; }
        public Nullable<decimal> RMACount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Day { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
    }
}
